---
title       : Tracking Training Day - II
subtitle    : The Revenge
author      : G.Cerati, V.Innocente, M.Rovere
job         : CERN
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify      # {highlight.js, prettify, highlight}
hitheme     : twitter-bootstrap # sunburst      #
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone,draft}

---
## Goals

We hope that, by today, you will become proficient in

* <font class="red bold">locate and browse tracking-related code</font>
* <font class="red bold">find samples for development and testing</font>
* <font class="red bold">run track reconstruction sequence</font> (default or modified)
    * check also timing and memory usage
* <font class="red bold">refit tracks</font>
* <font class="red bold">analyze tracks using EDM root files and plain ROOT</font>
* <font class="red bold">analyze tracks with EDAnalyzer</font>
    * <font class="blue bold">Step 1 -</font> select tracks, track parameters and `HitPattern`
    * <font class="blue bold">Step 2 -</font> hits properties
    * <font class="blue bold">Step 3 -</font> seeds and trajectories
    * <font class="blue bold">Step 4 -</font> seeding efficiency w.r.t tracking
* <font class="red bold">run track validation code</font>
    * MultiTrackValidator
* <font class="red bold">Advanced debugging</font>

--- .segue .dark .nobackground
## Prerequisites

---
## Setup a development area

We will be working with `CMSSW_7_2_0` release, using some ad-hoc
package that we have prepared for this training.

* Setup a development aread

<pre data-lang="shell">
<b>ssh -Y lxplus.cern.ch</b>
cd scratch0
mkdir TrackingTutorial
cd TrackingTutorial
<b>cmsrel CMSSW_7_2_0
cd CMSSW_7_2_0/src
cmsenv</b>
</pre>

* To facilitate the access to your own github repository w/o
  constantly typing your passphrase, do:

<pre data-lang="shell">
eval `ssh-agent`
ssh-add
</pre>

* Setup an empty git repository for the CMSSW area you just created

<pre data-lang="git">
git cms-init
</pre>

---
## Setup a development area

* Add the code for the Tracking Training Day II

<pre data-lang="shell">
git submodule add git@github.com:/rovere/TTD TTD
</pre>

* Different Steps of the exercises related to the `EDAnalyzer` part of
  the training are stored in different branches in github.

    * If you want to explore/modify code for a specific step, please
      remember to checkout the proper branch

 <pre data-lang="shell/git">
 cd src/TTD
 <b>git checkout step1</b>
 </pre>


* <font class="bold red">The code contained in the TTD package that you
  just downloaded it fully functional and contains the final version
  of the exercises that you will be asked to develop and run: be kind
  to yourself and do not start from them and, in case, use the code
  there only in case of troubles or as a reference.</font>

--- .segue .nobackground .dark
## Locate and browse tracking code

---
## Tracking Packages

* The main tracking packages are:
    * <font class="bold red">DataFormats</font>
        * [TrackReco](https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrackReco/), [TrajectorySeed](https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrajectorySeed/), [TrackingRecHit](https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrackingRecHit/), ...
    * <font class="bold red">RecoTracker</font>
        * contains the bulk of the reconstruction code
    * <font class="bold red">TrackingTools</font>
        * common utilities shared with muon tracking
* The recommended access point to browse code is `CMSSW LXR` main page at [https://cmssdt.cern.ch/SDT/lxr/](https://cmssdt.cern.ch/SDT/lxr/)
    * it is much more that a code browser and allows you to, e.g.:
        * search specific identifiers (class, variable, functions, ...)
        * follow code by clicking directly into the code
        * free text search with (limited) regexp capabilities
* Let's open few of them:
    * [https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrackReco/interface/Track.h](https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrackReco/interface/Track.h)
    * [https://cmssdt.cern.ch/SDT/lxr/source/RecoTracker/IterativeTracking/python/iterativeTk_cff.py](https://cmssdt.cern.ch/SDT/lxr/source/RecoTracker/IterativeTracking/python/iterativeTk_cff.py)
    * [https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrajectorySeed/interface/TrajectorySeed.h](https://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrajectorySeed/interface/TrajectorySeed.h)
    * [https://cmssdt.cern.ch/SDT/lxr/source/TrackingTools/PatternTools/interface/Trajectory.h](https://cmssdt.cern.ch/SDT/lxr/source/TrackingTools/PatternTools/interface/Trajectory.h)

--- .segue .nobackground .dark
## Sample Discovery

---
## Finding samples

* We will use the official CMS sample-discovery tool, DAS, via its CLI, `das_client.py`

* The best samples for developing and testing Tracking are RelVal.

* Typical developments do not need huge datasets: RelVals are made for
every (pre-) release and thus are always up to date.

    * <font class="bold yellow">They contain all the information
      needed (clusters, tracks, mc truth) that won’t be available on
      other samples.</font>

* Let’s start from a <font class="bold red">SingleMu</font> sample. We want it to be at CERN for a quick access:

<pre>
das_client.py --query='dataset dataset=/RelValSingleMu*/*CMSSW_7_2_0*/GEN-SIM-RECO' --format=plain --limit=0
</pre>

* Now, let’s choose Pt100 and find the files:

<pre>
das_client.py --query='file dataset=/RelValSingleMuPt100_UP15/CMSSW_7_2_0_pre3-POSTLS172_V3-v1/GEN-SIM-RECO' \
--format=plain \
--limit=0
</pre>

* Another useful sample is <font class="bold red">TTbar</font>:

<pre>
das_client.py --query='dataset dataset=/RelValTTbar*/*CMSSW_7_2_0*/GEN-SIM-RECO' \
--format=plain \
--limit=0
</pre>

---
## Finding samples

* Let’s pick the 13TeV inclusive sample with PU:

<pre>
das_client.py --query='file dataset=/RelValTTbar_13/CMSSW_7_2_0_pre5-PU25ns_POSTLS172_V3-v1/GEN-SIM-RECO' \
--format=plain \
--limit=0
</pre>

* For validation we will need also the GEN-SIM-DIGI-RAW-HLTDEBUG
  files
*  <font class="bold red">SingleMu</font>

<pre>
das_client.py \
--query='file dataset=/RelValSingleMuPt100_UP15/CMSSW_7_2_0_pre3-POSTLS172_V3-v1/GEN-SIM-DIGI-RAW-HLTDEBUG' \
--format=plain \
--limit=0
</pre>

*  <font class="bold red">TTbar</font>

<pre>
das_client.py \
--query='file dataset=/RelValTTbar_13/CMSSW_7_2_0_pre5-PU25ns_POSTLS172_V3-v1/GEN-SIM-RAW-HLTDEBUG' \
--format=plain \
--limit=0
</pre>


--- .segue .nobackground .dark
## Run Track Reconstruction

---
## Run Default Reco Sequence

* We need a configuration file with standard setting to run the default tracking
sequence.

* A file was already prepared for you: let’s take a look at it:

<pre>
emacs TTD/DemoTrackAnalyzer/test/recoTrk_cfg.py &
</pre>

* The main ingredients are:
    * input file,
    * GlobalTag
    * default services&sequences.

* RECO files store clusters, not hits. Before running tracking we need
to produce hits and add some other mandatory ingredient:

<pre data-lang="python">
# need to recreate hits from clusters (which are stored in RECO)
process.clustToHits = cms.Sequence(
    process.siPixelRecHits*process.siStripMatchedRecHits
)

# This is needed for tracking to work properly
process.load("RecoTracker.MeasurementDet.MeasurementTrackerEventProducer_cfi")
process.load("RecoPixelVertexing.PixelLowPtUtilities.siPixelClusterShapeCache_cfi")
</pre>

---
## Run Default Reco Sequence

* Now let’s run it:

<pre>
cmsRun recoTrk_cfg.py
</pre>

* Open the output file and look for the tracks we have made.

<pre data-lang="ROOT">
root -l reco_trk.root
TBrowser b
Events->Draw("recoTracks_generalTracks__RERECO.@obj.size()")
Events->Draw("recoTracks_generalTracks__RERECO.obj.chi2_")
Events->Draw("recoTracks_generalTracks__RERECO.obj.algorithm_")
Events->Draw("sqrt(recoTracks_generalTracks__RERECO.obj.momentum_.perp2())")
</pre>

* Enable services for timing summary and memory info and re-run.

---
## Run Custom Reco Sequence

* What are the exact parameters we have used in the default
  reconstruction?

    * For example, what are the layers used for seeding the initial
      step of iterative tracking?

<pre>
edmConfigDump recoTrk_cfg.py >& dump.recoTrk_cfg.txt
less dump.recoTrk_cfg.txt
</pre>

* Look for `process.initialStepSeeds` and then for
  `initialStepSeedLayers`.

* `initialStepSeedLayers` is the `SeedingLayers` definition of
  `initialStepSeeds`, and contains the list of layers used to produce
  the seeds

* Let’s modify the `layerList` by removing the first combination, i.e:
  `BPix1+BPix2+BPix3`

    * What differences would you expect?

---
## Run Custom Reco Sequence

* What are the exact parameters we have used in the default
  reconstruction?

    * For example, what are the layers used for seeding the initial
      step of iterative tracking?

<pre>
edmConfigDump recoTrk_cfg.py >& dump.recoTrk_cfg.txt
less dump.recoTrk_cfg.txt
</pre>

* Look for `process.initialStepSeeds` and then for
  `initialStepSeedLayers`.

* `initialStepSeedLayers` is the `SeedingLayers` definition of
  `initialStepSeeds`, and contains the list of layers used to produce
  the seeds

* Let’s modify the `layerList` by removing the first combination, i.e:
  `BPix1+BPix2+BPix3`

    * What differences would you expect?

* Modify the output file name to `reco_trk_mod.root` and add the
  following lines to `recoTrk_cfg.py`, run and look at the output file:

<pre data-lang="python">
process.initialStepSeedLayers.layerList = cms.vstring('BPix1+BPix2+FPix1_pos',
                                                      'BPix1+BPix2+FPix1_neg',
                                                      'BPix1+FPix1_pos+FPix2_pos',
                                                      'BPix1+FPix1_neg+FPix2_neg')
</pre>
<pre data-lang="ROOT">
cmsRun recoTrk_cfg.py
root -l -n reco_trk_mod.root
Events->Draw("recoTracks_generalTracks__RERECO.obj.algorithm_")
</pre>

---
## Run Custom Reco Sequence <font class="bold yellow">[python]</font>

<font class="bold red">Pythonic alternative method to perform the same actions</font>

<pre data-lang="python">
python -i recoTrk_cfg.py
>>> <b>process.initialStepSeeds</b>
cms.EDProducer("SeedGeneratorFromRegionHitsEDProducer",
    OrderedHitsFactoryPSet = cms.PSet(
        ComponentName = cms.string('StandardHitTripletGenerator'),
        ...
        SeedingLayers = cms.InputTag("initialStepSeedLayers")
    ),
</pre>

<pre data-lang="python">
>>> process.initialStepSeeds.getParameter('OrderedHitsFactoryPSet')
cms.PSet(
    ComponentName = cms.string('StandardHitTripletGenerator'),
    ...
    SeedingLayers = cms.InputTag("initialStepSeedLayers")
)
>>>
</pre>

<pre data-lang="python">
>>> process.initialStepSeedLayers
cms.EDProducer("SeedingLayersEDProducer",
    layerList = cms.vstring('BPix1+BPix2+BPix3',
        'BPix1+BPix2+FPix1_pos',
        'BPix1+BPix2+FPix1_neg',
        'BPix1+FPix1_pos+FPix2_pos',
        'BPix1+FPix1_neg+FPix2_neg'),
...
</pre>

---
## Run Custom Reco Sequence <font class="bold yellow">[python]</font>

<font class="bold red">Pythonic alternative method to perform the same actions</font>

Look also at the specific code that has been put into the
`recoTrk_cfg.py` file and uncomment the customization line at will.

<pre data-lang="python">
### CUSTOMIZATION FUNCTIONS TO BE USED ###

# CUSTOMIZE LAYERS USED TO PRODUCE SEEDS IN THE INITIAL_STEP
def customize_initialStepSeeds(process):
    process.initialStepSeedLayers.layerList.remove('BPix1+BPix2+BPix3')
    process.out.fileName = cms.untracked.string('reco_trk_mod.root')
    return process

### INVOKE APPROPRIATE CUSTOMIZATION FUNCTION(S) ###

# process = customize_initialStepSeeds(process)
</pre>


--- .segue .nobackground .dark
## Refit Tracks

---
## Refit Tracks

A very useful tool is the <font class="bold red">TrackRefit</font>.

* It takes as input the track collection and refits the tracks with
the same or with modified conditions (alignment, magnetic field) or
algorithms (propagator, cluster parameter estimator).

* <font class="green">Refitting tracks gives access to useful objects,
like hits positions and the trajectory (see later), and it is much
faster than full re-tracking</font>.

* Inspired from
[`RecoTracker/TrackProducer/test/TrackRefit.py`](https://cmssdt.cern.ch/SDT/lxr/source/RecoTracker/TrackProducer/test/TrackRefit.py),
a configuration file for refitting track was prepared.

* open the cfg

<pre>
emacs TTD/DemoTrackAnalyzer/test/refitTrk_cfg.py &
</pre>

* Where is the TrackRefitter module defined? Can you browse the code
  and find it?

* Now we can run it and compare original and refitted tracks:

<pre data-lang="ROOT">
root -l -n refit_trk_analytical.root
TCanvas c1
Events->Draw("sqrt(recoTracks_TrackRefitter__Refitting.obj.momentum_.perp2())")
TCanvas c2
Events->Draw("sqrt(recoTracks_generalTracks__RERECO.obj.momentum_.perp2())")
</pre>

---
## Refit Tracks

* What if we want to refit tracks under different conditions?

    * e.g., we may want to neglect energy loss (and detailed magnetic
field description from Runge Kutta propagation).

* We can add the following lines to `refitTrk_cfg.py`:

<pre data-lang="python">
process.TrackRefitter.Propagator = cms.string('AnalyticalPropagator')
process.RKTrajectoryFitter.Propagator = cms.string('AnalyticalPropagator')
process.RKTrajectorySmoother.Propagator = cms.string('AnalyticalPropagator')
</pre>

* What would you expect?

Now, let’s open again the file and check how big was the effect.

--- .segue .nobackground .dark
## Analyze Tracks with EDAnalyzer

---
## Preparing an EDAnalyzer

* Luckily, there is a simple command (`mkedanlzr`) to generate the
skeleton of an `EDAnalyzer` accessing tracks and making plots.

<pre>
mkdir TrackingTests
cd TrackingTests/
mkedanlzr DemoTrackAnalyzer example_track example_histo
cd DemoTrackAnalyzer/
mv python/ConfFile_cfg.py demoTrackAnalyzer_cfg.py
</pre>

* you need to edit the following files:

<pre>
emacs plugins/DemoTrackAnalyzer.cc plugins/BuildFile.xml demoTrackAnalyzer_cfg.py &
</pre>

* Then we can compile, run and open the output file with the usual
commands:

<pre>
scramv1 b -j 8
cmsRun demoTrackAnalyzer_cfg.py
root -l trackAnalysis.root
</pre>

<font class="red bold">But before, let’s edit it step by step</font>.

---
## Step 1: track variables&hit patter


### Goal

As a first step we want to add the plot for the <font class="bold
red">track pT</font>, the <font class="bold red">number of crossed
layers</font> and the <font class="red bold">number of outer layers
with no hits</font>.

### Procedure

* The skeleton already contains the declaration of the output file, of
  a histogram and a loop over tracks where the histogram is filled.

* You can surely add the plot of the track pT. Any idea how to get the
  information about layers with/without hits?

* The config file needs to be slightly modified.

    * First replace the old collection name `ctfWithMaterialTracks`
      with the up-to-date `generalTracks`.

    * Also, `trackAnalysis.root` looks more appropriate than
      `histo.root`.

* Another option for the input collection is a <font class="bold red">custom selection</font>.

    * A very useful tool is the string-based `TrackSelector`, for
      example:

---
## Step 1: track variables&hit patter

<pre data-lang="python">
process.selectedTracks = cms.EDFilter('TrackSelector',
                                      src = cms.InputTag('generalTracks'),
                                      cut = cms.string("quality('highPurity') & (algo=4) & abs(eta)&lt;0.9")
)
</pre>

### Worked-out example

<pre data-lang="git">
cd $LOCALRT/src/TTD
git branch --track TTD2_step1 remotes/origin/TTD2_step1
git checkout TTD2_step1
</pre>

* <font class="bold red">Let’s do something more advanced in the next
  step</font>.

---
## Step 2: Access to hit information - 1

* Tracking analyses are often related to <font class="bold red">hit
properties</font>. In this step we’ll learn how to access hits on a
track and hits from the inclusive hit collection.

* The main ingredient that is needed is the `TrackRefitter` (well,
  assuming you are not already performing a full reco step).

* In fact, <font class="bold red">hits stored on disk</font>
[(`TrackingRecHit`)](http://cmssdt.cern.ch/SDT/lxr/source/DataFormats/TrackingRecHit/interface/TrackingRecHit.h)
miss some relevant information:

    * <font class="bold red">local position is not stored and depends
      on the track direction hypothesis; therefore hits on track need
      to be refitted</font>;

    * they do not contain information about the tracker geometry that
      is needed to translate local into global position;

* We already know how to run the Refitter, so we can add it to cfg
  file and use tracks from the refitter as input (keep in mind that to
  do this you need also the globalTag and the standard includes).

---
## Step 2: Access to hit information - 2

### Goals

* We want to plot 2D maps of the hits, on the ZR plane for the hits on
  track and on the XY plane for all pixel barrel hits.

* Also, for pixel hits, we want to know how the various layers are
  populated (number of hits per layer).

### Procedure

* First we should include TH2.h, then declare and book the histograms:
  what are sensible ranges and binning?

* Can you find out how to loop over track hits?

* Once you found it you can then fill the ZR map with the proper
  information.

* To access pixel hits, as you recall, first we need to add
  `process.siPixelRecHits` to the `Path` because only clusters are
  saved in RECO data format.

* To discover in which part of the detector a specific hit is located
  we will use `TrackerTopology`'s methods queried using the `DetId`
  associated to each hit.

<pre data-lang="c++">
#include "DataFormats/TrackerCommon/interface/TrackerTopology.h"
</pre>

<pre data-lang="Buildfile">
&lt;use name="DataFormats/TrackerCommon"/&gt;
</pre>

---
## Step 2: Access to hit information - 3

* For the pixel hits part, you should add the following code to the C++

<pre data-lang="C++" class="linenums">
// Retrieve tracker topology from geometry
ESHandle&lt;TrackerTopology&gt; tTopoHandle;
iSetup.get&lt;IdealGeometryRecord&gt;().get(tTopoHandle);
const TrackerTopology* const tTopo = tTopoHandle.product();
...
// Access to hit information: loop over all pixel hits
// auto --&gt; edmNew::DetSetVector&lt;SiPixelRecHit&gt;
for (auto const& pixel_rechit_per_detid : *pixelHits) {
  DetId hitId = pixel_rechit_per_detid.detId();
  for (auto const& a_pixel_rechit : pixel_rechit_per_detid) {
    if (a_pixel_rechit.isValid()) {
      if (hitId.subdetId() ==
          static_cast&lt;int&gt;(PixelSubdetector::PixelBarrel)) {
        h_hit_pixelbarrel_map_-&gt;Fill(a_pixel_rechit.globalPosition().x(),
                                     a_pixel_rechit.globalPosition().y());
        h_hit_pixel_layers_-&gt;Fill(tTopo-&gt;pxbLayer(hitId));
      } else {
        h_hit_pixel_layers_-&gt;Fill(3 + tTopo-&gt;pxfDisk(hitId));
      }
    }
  }
}
</pre>

* Do you understand the structure of this code?

* Could you do something similar for strips?

---
## Step 2: Access to hit information - 3

### Worked-out example

<pre data-lang="git">
cd $LOCALRT/src/TTD
git branch --track TTD2_steps remotes/origin/TTD2_step2
git checkout TTD2_step2
</pre>

---
## Step 3: Seeds and Trajectories - 1

Increasing complexity, two key components of tracking are <font
class="bold red">seeds</font> and the <font class="bold
blue">trajectory</font>.

### SEED

* The <font class="bold red">seed</font> is the starting point for
  track building and it is made of

   * a vector of hits

   * a trajectory state (i.e. track parameters) positioned on the last
     hit along the direction.

* The trajectory state stored in the seed is a persistent version
  (`PTrajectoryStateOnDet`) that needs to be converted to the usual
  `TrajectoryStateOnSurface` via a helper function that needs the
  `MagneticField` and the hit surface.

* Again, one can access the seed collection or the seed that
  originated a specific track.

### TRAJECTORY

* The <font class="blue bold">trajectory</font> is the object used
  during the track fit and is made (mainly) of a vector of
  `TrajectoryMeasurements`, where each measurement contains a hit plus
  the trajectory states (predicted and updated).

* Trajectories are not saved in EDM files but are put into the event
  when tracks are made (either via full tracking or refitting).

* A trajectory-track map can be used to get one from the other.

---
## Step 3: Seeds and Trajectories - 2

### SEED - Goals

* We want to plot the $p_T$ of the seeds that originated a track and
  the pseudorapidity of all the seeds used in the `InitialStep`.

### Procedure

* Please declare and book the corresponding histograms.

* Include the headers:

<pre data-lang="C++">
#include "DataFormats/TrajectorySeed/interface/TrajectorySeed.h"
#include "DataFormats/TrajectorySeed/interface/TrajectorySeedCollection.h"
#include "TrackingTools/TrajectoryState/interface/TrajectoryStateTransform.h"
#include "MagneticField/Engine/interface/MagneticField.h"
#include "MagneticField/Records/interface/IdealMagneticFieldRecord.h"
</pre>

* You need to declare a variable for the `MagneticField` and get it
  from the `EventSetup` (no name is needed in this case). Can you do
  it?

---
## Step 3: Seeds and Trajectories - 3

* Inside the track loop, get the track seed, convert the persistent
  state to a `TSOS` and fill the histogram with the seed $p_T$:

<pre data-lang="C++" class="linenums">
auto tkseed = itTrack.seedRef();
// To pick-up the last hit on the seed you can either use
// seed->recHits().first + (num_rechits_in_seed - 1) or use
// seed->recHits().second - 1.
TrajectoryStateOnSurface state = trajectoryStateTransform::transientState(
    tkseed->startingState(),
    (tkseed->recHits().second - 1)->surface(),
    magneticField.product());
h_seed_pt_->Fill(state.globalMomentum().perp());

</pre>

* Can you get the `InitialStep` seed collection, loop over it and fill
  the $\eta$ plot?

* Keep in mind that you also need to modify the BuildFile:

<pre data-lang="Buildfile">
&lt;use name="MagneticField/Engine"/&gt;
&lt;use name="TrackingTools/TrajectoryState"/&gt;
</pre>

* Remember that the seed collection is not stored in RECO, so you need to
  re-run the tracking to get access

    * modify the cfg file accordingly.

---
## Step 3: Seeds and Trajectories - 4

### TRAJECTORY - Goals

* Compute the pull (residual divided by error) of TOB hit local x positions with respect to the forward predicted state.

### Procedure

* Declare and book the histogram

* Include the proper headers

<pre data-lang="C++">
#include "TrackingTools/PatternTools/interface/Trajectory.h"
#include "TrackingTools/PatternTools/interface/TrajTrackAssociation.h"
</pre>

* Before the track loop, get the association map and initialize an
  iterator to the beginning of the map:

<pre data-lang="C++">
TrajTrackAssociationCollection::const_iterator tji;
iEvent.getByToken(genericSeeds_token_, genericSeeds);
iEvent.getByToken(trajTrackAssociation_token_, trajTrackAssociation);
tji = trajTrackAssociation-&gt;begin();
</pre>

* Don’t forget to increment (`++`) the iterator inside the track loop
  to keep the two collections in sync.

---
## Step 3: Seeds and Trajectories - 4

* Inside the track loop, get the trajectory, loop over the
  `TrajectoryMeasurements` and, if we are in TOB, fill the pull
  histogram:

<pre data-lang="C++" class="linenums">
// Access to Trajectory: pull distribution for TOB
Ref&lt;std::vector&lt;Trajectory&gt; &gt; traj = tji-&gt;key;
for (auto const& measurement : traj-&gt;measurements()) {
  TrackingRecHit::ConstRecHitPointer hit = measurement.recHit();
  DetId hitId = hit-&gt;geographicalId();
  if (hit-&gt;isValid() &&
      hitId.subdetId() == static_cast&lt;int&gt;(StripSubdetector::TOB)) {
    TrajectoryStateOnSurface fwdState = measurement.forwardPredictedState();
    float delta = hit-&gt;localPosition().x() - fwdState.localPosition().x();
    float err2 = hit-&gt;localPositionError().xx() +
        fwdState.localError().positionError().xx();
    if (err2) h_tob_xpull_-&gt;Fill(delta / sqrt(err2));
  }
}
</pre>

* Run it on 5k single muon events and 50 ttbar events: do you
  understand the results?

### Worked-out example

<pre data-lang="git">
cd $LOCALRT/src/TTD
git branch --track TTD2_step3 remotes/origin/TTD2_step3
git checkout TTD2_step3
</pre>


---
## Step 4: Seeding eff. w.r.t Tracking - 1

### Goal

* We want to see how many of the seeds created in a specific iteration
  have been fully reconstructed as a final `HighPurity` track.

### Procedure

* We need to get the proper <font class="bold blue">seed
  collection</font> for the iteration we want to monitor. Assuming you
  would like to monitor the `TobTec` iteration, can you find the
  proper `InputTag` that needs to be used to retrieve it?

* Once you have the seed collection, loop over the seeds and fill an
  histogram of their distribution as a function of $\eta$, computing
  $\eta$ using the `TSOS` of its last hit.

* You also need to get the <font class="bold blue">track
  collection</font> of `HighPurity` tracks that have been
  reconstructed using the algorithm that correspond to the iteration
  you would like to monitor. Can you find the link between the algo
  assignment and the iteration name/number?

    * <font class="bold yellow">Hint:</font> use a `TrackSelector`
      filter in your cfg file and its label as `InputTag` to have the
      collection of proper tracks available in the event.

---
## Step 4: Seeding eff. w.r.t Tracking - 2

* Loop over the selected tracks and fill an $\eta$ distribution.

* Always remember that the seed collections are not persisted on disk,
  to you will have to rerun full-tracking and take the temporary
  collection out of the event.

* Can you write a simple ROOT macro that takes the $\eta$ distribution
  you created in the previous points and draw their ratio?

* Did you expect the result you obtained?

### Worked-out example

<pre data-lang="git">
cd $LOCALRT/src/TTD
git branch --track TTD2_step4 remotes/origin/TTD2_step4
git checkout TTD2_step4
</pre>


--- .segue .nobackground .dark
## Run Track Validation Code

---
## Run Track Validation Code

* The tracking validation suite is located under the `Validation/RecoTrack` package.

* An example of typical configuration files are in the `test` directory:

    * `MultiTrackValidator_cfg.py` and `MTV_HARVESTING.py`

    * Copy it locally and open it:

<pre data-lang="SHELL">
cp ${CMSSW_RELEASE_BASE}/src/Validation/RecoTrack/test/MultiTrackValidator_cfg.py .
cp ${CMSSW_RELEASE_BASE}/src/Validation/RecoTrack/test/MTV_HARVESTING.py .
emacs MultiTrackValidator_cfg.py &
</pre>

* You need to run two separate steps in order to obtain the results:

    * A first step in which you book and fill all necessary histograms

    * A second step (called <font class="bold
      red">harvesting</font>). in which you aggregate statistics and
      compute efficiencies, fake rates, etc...

* You need to fix a few things before running (<font class="bold green">they will be fixed asap in release</font>):
    * Update files with the list we found with `das`
    * Update the globalTag
    * `GeometryPilot2_cff` is outdated, use `Geometry_cff` (<font class="bold green">fix queued in release</font>)

---
## Run Track Validation Code

* Run it!

<pre data-lang="SHELL">
cmsRun MultiTrackValidator_cfg.py
cmsRun MTV_HARVESTING.py
</pre>

* This will produce validation plots for all highPurity tracks (see
  how `cutsRecoTracks` selector is defined).

* You can add other collection names to
  `process.multiTrackValidator.label` (e.g. `generalTracks` or every
  iterative step as done in
  `Validation/RecoTrack/python/TrackValidation_cff.py`).

* <font class="bold red">Official validation plots for each release
  are at</font>:
  [clickMe](http://cmsdoc.cern.ch/cms/Physics/tracking/validation/MC/)

---
## Run Track Validation Code

* By default, each efficiency plot is made with a different
  selection. They are defined in:
  `Validation/RecoTrack/python/TrackingParticleSelectionsForEfficiency_cff.py`

* You can modify the `TrackingParticle` selection to test effciencies
  in a different phase space. 

* For example, in order to use the same selection for all plots you
  can do:

<pre data-lang="python">
process.multiTrackValidator.ptMinTP = cms.double(0.4)
process.multiTrackValidator.lipTP = cms.double(35.0)
process.multiTrackValidator.tipTP = cms.double(70.0)
process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.ptMin = cms.double(0.4)
process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.lip = cms.double(35.0)
process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.tip = cms.double(70.0)
process.multiTrackValidator.histoProducerAlgoBlock.TpSelectorForEfficiencyVsEta  =
        process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.clone()
process.multiTrackValidator.histoProducerAlgoBlock.TpSelectorForEfficiencyVsPhi  =
        process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.clone()
process.multiTrackValidator.histoProducerAlgoBlock.TpSelectorForEfficiencyVsPt   =
        process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.clone()
process.multiTrackValidator.histoProducerAlgoBlock.TpSelectorForEfficiencyVsVTXR =
        process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.clone()
process.multiTrackValidator.histoProducerAlgoBlock.TpSelectorForEfficiencyVsVTXZ =
        process.multiTrackValidator.histoProducerAlgoBlock.generalTpSelector.clone()
</pre>

--- .segue .nobackground .dark
## Advanced Debugging

---
## Debug Pattern Recognition

* This is only for reference (<font class="bold yellow">and for brave
  people!</font>).

* We won’t go over it at the training day.

* Checkout the `RecoTracker/CkfPattern` and
  `RecoTracker/MeasurementDet packages and compile with the debug
  option:

<pre data-lang="SHELL">
(cd $LOCALRT && env USER_CXXFLAG="-DEDM_ML_DEBUG" scramv1 b -j 8)
</pre>

* Enable the following categories for the message logger:

    * `TkStripMeasurementDet`,
    * `TkPixelMeasurementDet`, 
    * `CkfPattern`,
    * `CkfTrackCandidateMakerBase`

* Also, you may want to uncomment the following line in
  `RecoTracker/CkfPattern/src/TrajectorySegmentBuilder.cc`:

<pre data-lang="C++">
//#define DBG_TSB
</pre>

* You may want to take a look at the customization function
  `customizeMessageLogger` in the `python/demo_customizations.py` file
  to have a rough understanding on how to properly configure the
  `MessageLogger` to convince it to make what you really want.


In this way, from a single seed you can follow the evolution of the combinatorial pattern recognition.

--- &thankyou
## Thank you!

Questions & Answers

